version: '3.8'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: poemshare
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - poemnet

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - poemnet

  backend:
    build: ./backend
    restart: unless-stopped
    env_file: ./backend/.env
    depends_on:
      - db
    ports:
      - '4000:4000'
    networks:
      - poemnet

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - '5173:5173'
    networks:
      - poemnet

  nginx:
    image: nginx:stable
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - poemnet

volumes:
  db-data:

networks:
  poemnet:
    driver: bridge
